server:
  port: 8080

spring:
  application:
    name: fluxpay

  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init-mode: always
